server:
  port: 8010

# CONEXION A BASE DE DATOS
spring:
  datasource:
    url: jdbc:postgresql://${SERVER_POSTGRES}:5431/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
# Hibernate ddl auto (create, create-drop, validate, update)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      jdbc:
        lob:
          non_contextual_creation: true
 # ESPECIFICACIONES DE KAFKA
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup

# TOPICO DE MENSAJERIA
topic:
   name: "TopicbitacoraSolicitud" 
