server:
  port: 8101
spring:
  jackson:
    date-format: com.righttek.ms.activarsubscripcion.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
# SERVICIOS A CONSUMIR
uri:
  SubscripcionComercialES: "http://localhost:8054"
  ConsultarCaracteristicasPorPlanComercial: "http://localhost:8075"
  ConsultarEmpresaPorId: "http://localhost:8076"
  ConsultarPagoPorOrden: "http://localhost:8078"
  ConsultarPlantillasNotificacionPorNombre: "http://localhost:8079"
  ConsultarSubscripcionComercialPorId: "http://localhost:8054"
  ConsultarUsuarioPorEmail: "http://localhost:8055"
  ConsultarValores: "http://localhost:8051"
  CrearCaracteristicasSubscripcion: "http://localhost:8050"
  CrearParametrosEmpresa: "http://localhost:8051"
  PlanComercialES:"http://localhost:8075"
  CaracteristicaSistemaPerfilES:"http://localhost:8067"
  ModuloES:"http://localhost:8069"
  PerfilES:"http://localhost:8066"
  RolES:"http://localhost:8063"
  UsuarioES:"http://localhost:8055"
  EnviarCorreo: "http://localhost:8056"
