server:
  port: 8087
spring:
  jackson:
    date-format: com.righttek.ms.activarsubscripcion.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
# SERVICIOS A CONSUMIR
uri:
  ActualizarSubscripcionComercial: localhost:8080
  ConsultarCaracteristicasPorPlanComercial: localhost:8080
  ConsultarEmpresaPorId: localhost:8080
  ConsultarPagoPorOrden: localhost:8080
  ConsultarPlantillasNotificacionPorNombre: localhost:8080
  ConsultarSubscripcionComercialPorId: localhost:8080
  ConsultarUsuarioPorEmail: localhost:8080
  ConsultarValores: localhost:8080
  CrearCaracteristicasSubscripcion: localhost:8080
  CrearParametrosEmpresa: localhost:8080
  EnviarCorreo: localhost:8080
