server:
  port: 8094

# ESPECIFICACIONES DE KAFKA
spring:
  kafka:
    bootstrap-servers: 10.35.2.65:9092
    consumer:
      group-id: myGroup


# SERVICIOS A CONSUMIR
uri:
  nomina-externa: "http://localhost:8082"
  esfuerzo-laboral: "http://localhost:8073"
  marcacion: "http://localhost:8071"
